import { CREATE_PAYMENT } from "./createPayment"
import {
  REGISTER,
  VERIFY,
  SET_PROFILE,
  LOGIN,
  FORGOT_PASSWORD,
  RESET_PASSWORD
} from "./auth"
import {
  GET_USER_BOOKINGS,
  UPDATE_PROFILE,
  UPDATE_PASSWORD,
  ME,
  FLIGHT_CANCELLATION
} from "./userProfile"

import { GET_CUSTOMERS } from "./customerList"

export {
  CREATE_PAYMENT,
  REGISTER,
  VERIFY,
  SET_PROFILE,
  LOGIN,
  FORGOT_PASSWORD,
  RESET_PASSWORD,
  UPDATE_PASSWORD,
  GET_USER_BOOKINGS,
  UPDATE_PROFILE,
  ME,
  FLIGHT_CANCELLATION,
  GET_CUSTOMERS
}
